version: '3'
services:
  master:
    container_name: master_service
    restart: always
    build: ./master/
    ports:
      - "5001:5000"
    depends_on:
      - slave
    environment:
      SLAVE_HOST: slave
      SLAVE_PORT: 5000
  slave:
    container_name: slave_service
    restart: always
    build: ./slave/
    ports:
      - "5000:5000"
